# Generated by Django 3.1.4 on 2020-12-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20201225_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('Firstname', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
