# Generated by Django 3.1.4 on 2020-12-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Firstname',
            new_name='Bio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
